import { db } from '@/db';
import { employees } from '@/db/schema';

async function main() {
    const sampleEmployees = [
        {
            firstName: 'Sarah',
            lastName: 'Johnson',
            email: 'sarah.johnson@company.com',
            position: 'Manager',
            department: 'Engineering',
            salary: 145000,
            hireDate: new Date('2019-03-15').toISOString(),
            phone: '+1-555-234-5678',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Michael',
            lastName: 'Chen',
            email: 'michael.chen@company.com',
            position: 'Senior Developer',
            department: 'Engineering',
            salary: 125000,
            hireDate: new Date('2020-06-01').toISOString(),
            phone: '+1-555-345-6789',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Priya',
            lastName: 'Patel',
            email: 'priya.patel@company.com',
            position: 'Senior Developer',
            department: 'Engineering',
            salary: 128000,
            hireDate: new Date('2020-09-18').toISOString(),
            phone: '+1-555-456-7890',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Emily',
            lastName: 'Rodriguez',
            email: 'emily.rodriguez@company.com',
            position: 'Developer',
            department: 'Engineering',
            salary: 95000,
            hireDate: new Date('2021-08-20').toISOString(),
            phone: '+1-555-567-8901',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Marcus',
            lastName: 'Washington',
            email: 'marcus.washington@company.com',
            position: 'Developer',
            department: 'Engineering',
            salary: 92000,
            hireDate: new Date('2022-02-14').toISOString(),
            phone: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'David',
            lastName: 'Kim',
            email: 'david.kim@company.com',
            position: 'Junior Developer',
            department: 'Engineering',
            salary: 68000,
            hireDate: new Date('2023-01-10').toISOString(),
            phone: '+1-555-678-9012',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Jennifer',
            lastName: 'Williams',
            email: 'jennifer.williams@company.com',
            position: 'Manager',
            department: 'Marketing',
            salary: 130000,
            hireDate: new Date('2019-11-05').toISOString(),
            phone: '+1-555-789-0123',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Alex',
            lastName: 'Thompson',
            email: 'alex.thompson@company.com',
            position: 'Senior Designer',
            department: 'Marketing',
            salary: 110000,
            hireDate: new Date('2020-09-12').toISOString(),
            phone: '+1-555-890-1234',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Nina',
            lastName: 'Kowalski',
            email: 'nina.kowalski@company.com',
            position: 'Marketing Specialist',
            department: 'Marketing',
            salary: 78000,
            hireDate: new Date('2022-05-23').toISOString(),
            phone: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Robert',
            lastName: 'Martinez',
            email: 'robert.martinez@company.com',
            position: 'Manager',
            department: 'Sales',
            salary: 140000,
            hireDate: new Date('2020-02-18').toISOString(),
            phone: '+1-555-901-2345',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Jessica',
            lastName: 'Nguyen',
            email: 'jessica.nguyen@company.com',
            position: 'Sales Representative',
            department: 'Sales',
            salary: 72000,
            hireDate: new Date('2023-04-03').toISOString(),
            phone: '+1-555-012-3456',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Lisa',
            lastName: 'Anderson',
            email: 'lisa.anderson@company.com',
            position: 'HR Manager',
            department: 'HR',
            salary: 125000,
            hireDate: new Date('2019-07-22').toISOString(),
            phone: '+1-555-123-4567',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Omar',
            lastName: 'Hassan',
            email: 'omar.hassan@company.com',
            position: 'HR Coordinator',
            department: 'HR',
            salary: 65000,
            hireDate: new Date('2023-06-15').toISOString(),
            phone: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'James',
            lastName: 'Taylor',
            email: 'james.taylor@company.com',
            position: 'Finance Manager',
            department: 'Finance',
            salary: 135000,
            hireDate: new Date('2020-04-30').toISOString(),
            phone: '+1-555-234-5670',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            firstName: 'Amanda',
            lastName: 'Garcia',
            email: 'amanda.garcia@company.com',
            position: 'Accountant',
            department: 'Finance',
            salary: 85000,
            hireDate: new Date('2022-03-14').toISOString(),
            phone: '+1-555-345-6781',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(employees).values(sampleEmployees);
    
    console.log('✅ Employees seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});